[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && /opt/venv/bin/python server.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3