[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -c 'cd backend && python server.py'"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3